server:
  port: 9600

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  routes:
    api-members:
      path: /api-m/**
      serviceId: members-services
#    api-goods:
#      path: /v1/api/goods/**
#      serviceId: members-services

