server:
  port: 9211

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:9000/eureka"

spring:
  application:
    name: members-services
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/workplace?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true
